const WEEKLY_GOALS = {
  run: 2,
  swim: 2,
  iron: 3,
  mindfulness: 2
};

const LEVEL_XP = 2000;

const STRAVA_AFTER_TIMESTAMP = 1767225600;
const STRAVA_PER_PAGE = 100;

const ARENA_DEFAULT_DURATION_DAYS = 7;
const ARENA_DRAW_REFUND_RATE = 0.85;
const ARENA_PROGRESS_CACHE_MS = 60000;
const DEFAULT_ARENA_START_GRACE_MINUTES = 720;

const IRON_PROTOCOL_TYPES = new Set([
  "WeightTraining",
  "Workout",
  "Crossfit"
]);
const MINDFULNESS_TYPES = new Set(["Yoga", "Meditation", "Mindfulness"]);
const ARENA_GYM_TYPES = new Set([
  ...IRON_PROTOCOL_TYPES,
  ...MINDFULNESS_TYPES,
  "Iron Protocol"
]);

const MINDFULNESS_MIN_SECONDS = 0;
const MIN_TRACKED_DISTANCE_METERS = 100;

const RUN_REWARD_DISTANCE_METERS = 5000;
const SWIM_REWARD_DISTANCE_METERS = 1000;
const RUN_REWARD = 10;
const SWIM_REWARD = 20;
const IRON_REWARD = 10;
const MINDFULNESS_REWARD = 10;

const INVESTOR_TARGET = 500;
const INVESTOR_XP_BONUS = 50;

const XP_CHALLENGE_STATUSES = [
  "completed",
  "claim_completato",
  "resolved",
  "claimed"
];

module.exports = {
  WEEKLY_GOALS,
  LEVEL_XP,
  STRAVA_AFTER_TIMESTAMP,
  STRAVA_PER_PAGE,
  ARENA_DEFAULT_DURATION_DAYS,
  ARENA_DRAW_REFUND_RATE,
  ARENA_PROGRESS_CACHE_MS,
  DEFAULT_ARENA_START_GRACE_MINUTES,
  IRON_PROTOCOL_TYPES,
  MINDFULNESS_TYPES,
  ARENA_GYM_TYPES,
  MINDFULNESS_MIN_SECONDS,
  MIN_TRACKED_DISTANCE_METERS,
  RUN_REWARD_DISTANCE_METERS,
  SWIM_REWARD_DISTANCE_METERS,
  RUN_REWARD,
  SWIM_REWARD,
  IRON_REWARD,
  MINDFULNESS_REWARD,
  INVESTOR_TARGET,
  INVESTOR_XP_BONUS,
  XP_CHALLENGE_STATUSES
};
